---
# --- Connection Defaults ---
ansible_user: "ansible"
ansible_ssh_private_key_file: "~/.ssh/ansible_homelab"
ansible_become_method: sudo
ansible_python_interpreter: /usr/bin/python3

# --- Regional Settings ---
timezone: "America/Los_Angeles"

# --- Homelab Metadata ---
domain_name: "dino.computer"
ansible_user_pub_key: "{{ lookup ('file', '~/.ssh/ansible_homelab.pub') }}"